-- MySQL Script generated by MySQL Workbench
-- Sun Oct 20 15:45:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema_booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema_booking` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cinema_booking` ;

-- -----------------------------------------------------
-- Table `cinema_booking`.`AccountState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`AccountState` (
  `state` ENUM('active', 'inactive', 'suspended') NOT NULL,
  PRIMARY KEY (`state`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Admin` (
  `user_id` INT NULL DEFAULT NULL,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `admin_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema_booking`.`User` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_verified` TINYINT(1) NULL DEFAULT NULL,
  `subscribedToPromotions` TINYINT(1) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `account_state` ENUM('active', 'inactive', 'suspended') NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `customer_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema_booking`.`User` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `release_date` DATE NULL DEFAULT NULL,
  `trailer_link` VARCHAR(255) NULL DEFAULT NULL,
  `img_link` VARCHAR(255) NULL DEFAULT NULL,
  `cast` TEXT NULL DEFAULT NULL,
  `director` VARCHAR(255) NULL DEFAULT NULL,
  `producers` TEXT NULL DEFAULT NULL,
  `mpaa_rating` VARCHAR(10) NULL DEFAULT NULL,
  `reviews` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Showroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Showroom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Showtime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Showtime` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `movie_id` INT NULL DEFAULT NULL,
  `showroom_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `movie_id` (`movie_id` ASC) VISIBLE,
  INDEX `showroom_id` (`showroom_id` ASC) VISIBLE,
  CONSTRAINT `showtime_ibfk_1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinema_booking`.`Movie` (`id`),
  CONSTRAINT `showtime_ibfk_2`
    FOREIGN KEY (`showroom_id`)
    REFERENCES `cinema_booking`.`Showroom` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `online_booking_fee` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `showtime_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `showtime_id` (`showtime_id` ASC) VISIBLE,
  CONSTRAINT `booking_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cinema_booking`.`Customer` (`id`),
  CONSTRAINT `booking_ibfk_2`
    FOREIGN KEY (`showtime_id`)
    REFERENCES `cinema_booking`.`Showtime` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Promotion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expiry` DATE NULL DEFAULT NULL,
  `percent_off` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`BookingPromotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`BookingPromotion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NULL DEFAULT NULL,
  `promotion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `booking_id` (`booking_id` ASC) VISIBLE,
  INDEX `promotion_id` (`promotion_id` ASC) VISIBLE,
  CONSTRAINT `bookingpromotion_ibfk_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `cinema_booking`.`Booking` (`id`),
  CONSTRAINT `bookingpromotion_ibfk_2`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `cinema_booking`.`Promotion` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`PaymentCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`PaymentCard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(16) NULL DEFAULT NULL,
  `expiry_date` DATE NULL DEFAULT NULL,
  `billing_address` TEXT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `paymentcard_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cinema_booking`.`Customer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Seat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL DEFAULT NULL,
  `showroom_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `showroom_id` (`showroom_id` ASC) VISIBLE,
  CONSTRAINT `seat_ibfk_1`
    FOREIGN KEY (`showroom_id`)
    REFERENCES `cinema_booking`.`Showroom` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`TicketType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`TicketType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema_booking`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema_booking`.`Ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NULL DEFAULT NULL,
  `ticket_type_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `booking_id` (`booking_id` ASC) VISIBLE,
  INDEX `ticket_type_id` (`ticket_type_id` ASC) VISIBLE,
  CONSTRAINT `ticket_ibfk_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `cinema_booking`.`Booking` (`id`),
  CONSTRAINT `ticket_ibfk_2`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `cinema_booking`.`TicketType` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
