POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "admin@example.com", "password": "123" }


###
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
  "user": {
    "username": "johndoe1234567890@example.com",
    "password": "securepassword"
  },
  "email": "johndoe1234567890@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": "1234567890",
  "address": "123 Main St",
  "email_verified": false,
  "subscribed_to_promotions": true,
  "account_state": "active"
}

###
POST http://127.0.0.1:8000/create_admin
Content-Type: application/json

{
    "user": {
        "username": "admin@example.com",
        "password": "123"
    },
    "email": "admin@example.com",
    "first_name": "Admin",
    "last_name": "User"
}





###
GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: Token dbbd53f80d60307b799f4c507f8b0de595f378e0

{}

###
POST http://127.0.0.1:8000/v1/showtimes/movies/1
Content-Type: application/json
Authorization: Token 42f880e5a5697f70ac09c7870b43db08c614ecf2

{
  "showroom": "a1",
  "time": "2024-12-09 15:00:00",
  "duration": 120
}
