# Generated by Django 4.2.16 on 2024-10-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trailer_link', models.CharField(max_length=500)),
                ('img_link', models.CharField(max_length=500)),
                ('duration', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'db_table': 'Movie',
            },
        ),
    ]
