# Generated by Django 4.2.16 on 2024-10-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_customer_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_verified',
        ),
    ]
