# Generated by Django 4.2.16 on 2024-10-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_customer_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
