# Generated by Django 4.2.16 on 2024-12-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_booking_movie_title_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='card_number',
            field=models.CharField(default=1234, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='last_four_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
