# Generated by Django 4.2.16 on 2024-12-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_booking_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='showtime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.showtime'),
        ),
    ]
