# Generated by Django 4.2.16 on 2024-10-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_customer_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='default@admin.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
