# Generated by Django 4.2.16 on 2024-12-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_paymentcard_card_number_paymentcard_last_four_digits'),
        ('v1', '0005_remove_booking_show_time_ticket_showtime'),
    ]

    operations = [
    ]
