# Generated by Django 4.2.16 on 2024-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_merge_20241209_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='seat_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
