# Generated by Django 4.2.16 on 2024-12-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_showroom_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
