# Generated by Django 4.2.16 on 2024-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alter_promotion_end_date_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
